# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faaa6fecb6f8026a9bac951d9dd905b3d7d81f0edaee3ef50c747a6d71a498506a423c6739d60d852dd67819d79d36cc03bf71b5519a8629db2f01bba3e14881

test:
  secret_key_base: 5fd606f6db4b90c5dcc6e581b7180dc4de0de9fa857fc6d2a25b4e767d264aba87e0c7734ed68152b744a045037051b566bbcf912afd30de93ba1b32f844143b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
